CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE diseases (
    id uuid NOT NULL,
    name text NOT NULL,
    severity text NOT NULL,
    CONSTRAINT "PK_diseases" PRIMARY KEY (id)
);


CREATE TABLE doctors (
    id uuid NOT NULL,
    name text NOT NULL,
    specialty text NOT NULL,
    years_experience integer,
    CONSTRAINT "PK_doctors" PRIMARY KEY (id)
);


CREATE TABLE patients (
    id uuid NOT NULL,
    name text NOT NULL,
    birthdate date NOT NULL,
    gender boolean NOT NULL,
    address text,
    CONSTRAINT "PK_patients" PRIMARY KEY (id)
);


CREATE TABLE treatments (
    id uuid NOT NULL,
    name text NOT NULL,
    cost double precision NOT NULL,
    CONSTRAINT "PK_treatments" PRIMARY KEY (id)
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE diagnoses (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    disease_id uuid NOT NULL,
    diagnosis_date timestamp with time zone,
    doctor_id uuid NOT NULL,
    CONSTRAINT "PK_diagnoses" PRIMARY KEY (id),
    CONSTRAINT "FK_diagnoses_diseases_disease_id" FOREIGN KEY (disease_id) REFERENCES diseases (id) ON DELETE CASCADE,
    CONSTRAINT "FK_diagnoses_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_diagnoses_patients_patient_id" FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
);


CREATE TABLE patient_treatments (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    treatment_id uuid NOT NULL,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    CONSTRAINT "PK_patient_treatments" PRIMARY KEY (id),
    CONSTRAINT "FK_patient_treatments_patients_patient_id" FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
    CONSTRAINT "FK_patient_treatments_treatments_treatment_id" FOREIGN KEY (treatment_id) REFERENCES treatments (id) ON DELETE CASCADE
);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_diagnoses_disease_id" ON diagnoses (disease_id);


CREATE INDEX "IX_diagnoses_doctor_id" ON diagnoses (doctor_id);


CREATE INDEX "IX_diagnoses_patient_id" ON diagnoses (patient_id);


CREATE INDEX "IX_patient_treatments_patient_id" ON patient_treatments (patient_id);


CREATE INDEX "IX_patient_treatments_treatment_id" ON patient_treatments (treatment_id);


