CREATE TABLE diseases (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    severity text NOT NULL,
    CONSTRAINT diseases_pkey PRIMARY KEY (id)
);


CREATE TABLE doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    specialty text NOT NULL,
    years_experience integer,
    CONSTRAINT doctors_pkey PRIMARY KEY (id)
);


CREATE TABLE patients (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    birthdate date NOT NULL,
    gender boolean NOT NULL,
    address text,
    CONSTRAINT patients_pkey PRIMARY KEY (id)
);


CREATE TABLE treatments (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    cost double precision NOT NULL,
    CONSTRAINT treatments_pkey PRIMARY KEY (id)
);


CREATE TABLE diagnoses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    patient_id integer NOT NULL,
    disease_id integer NOT NULL,
    diagnosis_date timestamp with time zone DEFAULT (CURRENT_TIMESTAMP),
    doctor_id integer NOT NULL,
    CONSTRAINT diagnoses_pkey PRIMARY KEY (id),
    CONSTRAINT diagnoses_disease_id_fkey FOREIGN KEY (disease_id) REFERENCES diseases (id) ON DELETE CASCADE,
    CONSTRAINT diagnoses_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT diagnoses_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
);


CREATE TABLE patient_treatments (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    patient_id integer NOT NULL,
    treatment_id integer NOT NULL,
    start_date timestamp with time zone DEFAULT (CURRENT_TIMESTAMP),
    end_date timestamp with time zone,
    CONSTRAINT patient_treatments_pkey PRIMARY KEY (id),
    CONSTRAINT patient_treatments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
    CONSTRAINT patient_treatments_treatment_id_fkey FOREIGN KEY (treatment_id) REFERENCES treatments (id) ON DELETE CASCADE
);


CREATE INDEX "IX_diagnoses_disease_id" ON diagnoses (disease_id);


CREATE INDEX "IX_diagnoses_doctor_id" ON diagnoses (doctor_id);


CREATE INDEX "IX_diagnoses_patient_id" ON diagnoses (patient_id);


CREATE INDEX "IX_patient_treatments_patient_id" ON patient_treatments (patient_id);


CREATE INDEX "IX_patient_treatments_treatment_id" ON patient_treatments (treatment_id);


